---
- name: Copy sources.list
  copy:
    src: debian9.list
    dest: /etc/apt/sources.list

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 86400  # one day

- name: Install common packages
  apt:
    name: [
      'git',
      'vim',
      'mc',
      'wget',
      'curl',
      'mutt',
      'htop',
    ]
    state: present
